SET NAMES utf8mb4;

#用户表单
CREATE TABLE IF NOT EXISTS `User` (
	`UserId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
	`UserName` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户名称',
	`UserNum` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户账号',
	`UserPassword` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户密码',
	`UserState` INT(11) UNSIGNED DEFAULT 0 COMMENT '用户权限状态' ,
	PRIMARY KEY (`userId`)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='用户表单';

#商铺表单
CREATE TABLE IF NOT EXISTS `Store`(
  `StoreId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商铺ID',
  `StoreName` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商铺名称',
  `StoreType` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商铺类型',
  `StorePhone` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商铺热线',
  `StoreLocation`VARCHAR(1000) DEFAULT '' COMMENT '商铺位置',
  `StoreRemark`VARCHAR(1000) DEFAULT '' COMMENT '商铺简介',
  `StoreState` INT(11) UNSIGNED DEFAULT 0 COMMENT '商铺状态' ,
  `CreateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `EndTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下架时间',
  `StorePicList` VARCHAR(100) DEFAULT '' COMMENT '图片',
  `UserId` INT(11) UNSIGNED DEFAULT 0 COMMENT '店长ID',
  PRIMARY KEY (`StoreId`)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='商铺表单';

#商品表单
CREATE TABLE IF NOT EXISTS `Commodity`(
  `CommodityId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商品ID',
  `CommodityName` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商品名称',
  `CommodityState` INT(11) UNSIGNED DEFAULT 0 COMMENT '商品状态' ,
  `CommodityPrice` DECIMAL(10,2) UNSIGNED DEFAULT 0 COMMENT '商品价格' ,
  `CommodityRemark`VARCHAR(1000) DEFAULT '' COMMENT '商品备注',
  `CreateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `EndTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下架时间',
  `CommodityPicList` VARCHAR(100) DEFAULT '' COMMENT '图片',
  `StoreId` INT(11) UNSIGNED DEFAULT 0 COMMENT '店铺ID',
  PRIMARY KEY (`CommodityId`)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='商品表单';

#活动表单
CREATE TABLE IF NOT EXISTS `Activity`(
  `ActivityId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '活动ID',
  `ActivityName` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '活动名称',
  `ActivityState` INT(11) UNSIGNED DEFAULT 0 COMMENT '活动状态' ,
  `ActivityRemark`VARCHAR(1000) DEFAULT '' COMMENT '活动备注',
  `ActivityDiscount` INT(11) UNSIGNED DEFAULT 10 COMMENT '活动折扣' ,
  `CreateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `EndTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结束时间',
  `ActivityPicList` VARCHAR(100) DEFAULT '' COMMENT '图片',
  `CommodityIdList` VARCHAR (100) DEFAULT '' COMMENT '商品ID集合',
  `StoreId` INT(11) UNSIGNED DEFAULT 0 COMMENT '店铺ID',
  PRIMARY KEY (`ActivityId`)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='活动表单';

#图片表单
CREATE TABLE IF NOT EXISTS `Picture`(
  `PictureId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图片ID',
  `PictureWay` VARCHAR(255) DEFAULT '' COMMENT '图片',
  PRIMARY KEY (`PictureId`)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='图片表单';

#商圈表单
CREATE TABLE IF NOT EXISTS `Trade`(
  `TradeId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商圈ID',
  `TradeName` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商圈名称',
  `TradePhone` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商圈热线',
  `TradeState` INT(11) UNSIGNED DEFAULT 0 COMMENT '商圈状态' ,
  `CreateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `EndTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结束时间',
  `TradeRemark`VARCHAR(1000) DEFAULT '' COMMENT '商圈简介',
  `TradeLocation`VARCHAR(1000) DEFAULT '' COMMENT '商圈位置',
  `TradePicList` VARCHAR(100) DEFAULT '' COMMENT '图片',
  `UserId` INT(11) UNSIGNED DEFAULT 0 COMMENT '商圈管理员ID',
  `StoreIdList` VARCHAR (100) DEFAULT '' COMMENT '店铺ID集合',
  PRIMARY KEY (`TradeId`)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='商圈表单';
