SET NAMES utf8mb4;

CREATE TABLE `activity` (
	`ActivityId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '活动ID',
	`ActivityName` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '活动名称',
	`ActivityState` INT(11) UNSIGNED NULL DEFAULT '1' COMMENT '活动状态',
	`ActivityRemark` VARCHAR(1000) NULL DEFAULT '' COMMENT '活动备注',
	`ActivityDiscount` INT(11) UNSIGNED NULL DEFAULT '10' COMMENT '活动折扣',
	`CreateTime` DATE NULL DEFAULT NULL COMMENT '创建时间',
	`EndTime` DATE NULL DEFAULT NULL COMMENT '结束时间',
	`ActivityPicIdList` VARCHAR(1000) NULL DEFAULT '0' COMMENT '图片',
	`StoreId` INT(11) UNSIGNED NULL DEFAULT '0' COMMENT '店铺ID',
	PRIMARY KEY (`ActivityId`)
)
COMMENT='活动表单'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `commodity` (
	`CommodityId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商品ID',
	`CommodityName` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商品名称',
	`CommodityState` INT(11) UNSIGNED NULL DEFAULT '1' COMMENT '商品状态',
	`CommodityPrice` DECIMAL(10,2) UNSIGNED NULL DEFAULT '0.00' COMMENT '商品价格',
	`CommodityRemark` VARCHAR(1000) NULL DEFAULT '' COMMENT '商品备注',
	`CreateTime` DATE NULL DEFAULT NULL COMMENT '创建时间',
	`EndTime` DATE NULL DEFAULT NULL COMMENT '下架时间',
	`CommodityPicIdList` VARCHAR(1000) NULL DEFAULT '0' COMMENT '图片',
	`StoreId` INT(11) UNSIGNED NULL DEFAULT '0' COMMENT '店铺ID',
	`DiscountAcId` INT(11) UNSIGNED NULL DEFAULT '0' COMMENT '折扣',
	`OtherAcId` INT(11) UNSIGNED NULL DEFAULT '0' COMMENT '其他活动',
	PRIMARY KEY (`CommodityId`)
)
COMMENT='商品表单'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `picture` (
	`PictureId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图片ID',
	`PictureWay` VARCHAR(1000) NULL DEFAULT '' COMMENT '图片',
	PRIMARY KEY (`PictureId`)
)
COMMENT='图片表单'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `store` (
	`StoreId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商铺ID',
	`StoreName` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商铺名称',
	`StoreType` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商铺类型',
	`StorePhone` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商铺热线',
	`StoreLocation` VARCHAR(1000) NULL DEFAULT '' COMMENT '商铺位置',
	`StoreRemark` VARCHAR(1000) NULL DEFAULT '' COMMENT '商铺简介',
	`StoreState` INT(11) UNSIGNED NULL DEFAULT '1' COMMENT '商铺状态',
	`CreateTime` DATE NULL DEFAULT NULL COMMENT '创建时间',
	`EndTime` DATE NULL DEFAULT NULL COMMENT '下架时间',
	`StorePicIdList` VARCHAR(1000) NULL DEFAULT '0' COMMENT '图片',
	`TradeId` INT(11) NULL DEFAULT NULL COMMENT '所属商圈ID',
	`UserId` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT '店长ID',
	PRIMARY KEY (`StoreId`)
)
COMMENT='商铺表单'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `trade` (
	`TradeId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商圈ID',
	`TradeName` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商圈名称',
	`TradePhone` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '商圈热线',
	`TradeState` INT(11) UNSIGNED NULL DEFAULT '1' COMMENT '商圈状态',
	`CreateTime` DATE NULL DEFAULT NULL COMMENT '创建时间',
	`EndTime` DATE NULL DEFAULT NULL COMMENT '结束时间',
	`TradeRemark` VARCHAR(1000) NULL DEFAULT '' COMMENT '商圈简介',
	`TradeLocation` VARCHAR(1000) NULL DEFAULT '' COMMENT '商圈位置',
	`TradePicIdList` VARCHAR(1000) NULL DEFAULT '0' COMMENT '图片',
	`UserId` INT(11) UNSIGNED NULL DEFAULT '0' COMMENT '商圈管理员ID',
	PRIMARY KEY (`TradeId`)
)
COMMENT='商圈表单'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `user` (
	`UserId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
	`UserName` VARCHAR(50) NULL DEFAULT '' COMMENT '用户名称',
	`UserNum` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户账号',
	`UserPassword` VARCHAR(50) NOT NULL DEFAULT '88888888' COMMENT '用户密码',
	`UserState` INT(11) UNSIGNED NULL DEFAULT '0' COMMENT '用户权限状态',
	PRIMARY KEY (`UserId`)
)
COMMENT='用户表单'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
